# =============================================================================
# PRE-COMMIT CONFIGURATION
# =============================================================================
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # =============================================================================
  # GENERAL CODE QUALITY
  # =============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # =============================================================================
  # PYTHON CODE FORMATTING & LINTING
  # =============================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      # Linting
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
      # Formatting
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py38]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # =============================================================================
  # SECURITY SCANNING
  # =============================================================================
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-r, -f, json, -o, bandit-report.json]
        exclude: tests/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: |
          (?x)^(
            \.secrets\.baseline|
            \.env\.example|
            tests/.*|
            .*\.lock$
          )$

  # =============================================================================
  # DEPENDENCY SECURITY
  # =============================================================================
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  # =============================================================================
  # DOCUMENTATION & MARKDOWN
  # =============================================================================
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(CHANGELOG\.md|\.github/)

  # =============================================================================
  # PYTHON IMPORTS SORTING
  # =============================================================================
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --expand-star-imports

# =============================================================================
# GLOBAL CONFIGURATION
# =============================================================================
default_language_version:
  python: python3.8

# Exclude patterns
exclude: |
  (?x)^(
    migrations/|
    __pycache__/|
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    build/|
    dist/|
    \.venv/|
    venv/|
    env/|
    \.env|
    node_modules/|
    \.idea/|
    \.vscode/|
    .*\.egg-info/|
    .*\.min\.(js|css)$
  )$

# Minimum supported pre-commit version
minimum_pre_commit_version: 3.0.0

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false