# Pre-commit hooks - see https://pre-commit.com/hooks.html
repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff          # Fast Python linter
        args: [--fix]
      - id: ruff-format   # Fast Python formatter

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit        # Security linter for Python
        args: [-r, -f, json, -o, bandit-report.json]
        exclude: tests/