# =============================================================================
# LOKI CONFIGURATION - ADVANCED LOG AGGREGATION
# =============================================================================

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 8388608
  grpc_server_max_send_msg_size: 8388608

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# =============================================================================
# QUERY CONFIGURATION
# =============================================================================
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# =============================================================================
# SCHEMA CONFIGURATION
# =============================================================================
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# =============================================================================
# RULER CONFIGURATION (for log-based alerts)
# =============================================================================
ruler:
  alertmanager_url: http://alertmanager:9093
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

# =============================================================================
# INGESTER CONFIGURATION
# =============================================================================
ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

# =============================================================================
# STORAGE CONFIGURATION
# =============================================================================
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# =============================================================================
# COMPACTOR CONFIGURATION
# =============================================================================
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

# =============================================================================
# LIMITS CONFIGURATION
# =============================================================================
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_streams_per_user: 10000
  max_line_size: 256000
  max_entries_limit_per_query: 5000
  max_query_series: 500
  max_query_parallelism: 32
  max_concurrent_tail_requests: 10

# =============================================================================
# TABLE MANAGER CONFIGURATION
# =============================================================================
table_manager:
  retention_deletes_enabled: false
  retention_period: 168h

# =============================================================================
# CHUNK STORE CONFIGURATION
# =============================================================================
chunk_store_config:
  max_look_back_period: 0s

# =============================================================================
# QUERY SCHEDULER CONFIGURATION
# =============================================================================
query_scheduler:
  max_outstanding_requests_per_tenant: 256

# =============================================================================
# FRONTEND CONFIGURATION
# =============================================================================
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true

# =============================================================================
# TRACING CONFIGURATION (Jaeger integration)
# =============================================================================
tracing:
  enabled: true