apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triage-data-pvc
  namespace: crewai-email-triage
  labels:
    app: email-triage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-encrypted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triage-logs-pvc
  namespace: crewai-email-triage
  labels:
    app: email-triage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc