# =============================================================================
# AUTOMATED DEPENDENCY UPDATES
# =============================================================================

name: 🔄 Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  # =============================================================================
  # DEPENDENCY SECURITY AUDIT
  # =============================================================================
  security-audit:
    name: 🔒 Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit

      - name: Run safety check
        run: |
          safety check --json --output safety-report.json || true
          safety check

      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: safety-report.json

  # =============================================================================
  # CREATE DEPENDENCY UPDATE PR
  # =============================================================================
  update-dependencies:
    name: 📦 Update Dependencies
    runs-on: ubuntu-latest
    needs: security-audit
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip pip-tools

      - name: Update dependencies
        run: |
          # Update development dependencies
          pip-compile --upgrade pyproject.toml --extra dev --output-file requirements-dev.txt
          
          # Update test dependencies  
          pip-compile --upgrade pyproject.toml --extra test --output-file requirements-test.txt
          
          # Update documentation dependencies
          pip-compile --upgrade pyproject.toml --extra docs --output-file requirements-docs.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update Python dependencies'
          title: '🔄 Automated dependency updates'
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated updates to Python dependencies.
            
            ### Changes
            - Updated development dependencies
            - Updated test dependencies
            - Updated documentation dependencies
            
            ### Security
            - All dependencies have been checked for security vulnerabilities
            - See security audit report in CI artifacts
            
            ### Testing
            - All CI checks must pass before merging
            - Manual testing may be required for major version updates
            
            ---
            *This PR was created automatically by the dependency update workflow.*
          branch: chore/update-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated
            chore